Implement `into_cosmos_msg` for `VaultStandardExecuteMsg` and `ExtensionExecuteMsg`
apollodao/cosmwasm-vault-standard pull request #26
Opened 2022-11-21 21:04 UTC by apollo-pacman

closes #24

2022-11-21 21:11 UTC, apollo-sturdy requested changes
Pls also do same for `Cw4626ExecuteMsg`.

2022-11-21 21:18 UTC, apollo-sturdy commented on src/msg.rs
> +}
Maybe makes more sense to impl it for the extension executemsgs themselves as users wont always have this collection enum if they define their owns et of extensions.

2022-11-22 15:37 UTC, apollo-pacman reviewed
lgtm @apollo-sturdy

2022-11-22 15:38 UTC, apollo-sturdy approved these changes

2022-11-22 15:39 UTC, merged